# Generated by Django 4.2.1 on 2023-06-04 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_task_priority_alter_task_description_alter_task_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklist',
            name='lists',
            field=models.ManyToManyField(related_name='lists', to='lists.task'),
        ),
    ]
