# Generated by Django 4.2.1 on 2023-06-04 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0003_tasklist_tasks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasklist',
            name='lists',
        ),
        migrations.AddField(
            model_name='tasklist',
            name='tasks',
            field=models.ManyToManyField(related_name='tasks', to='lists.task'),
        ),
    ]
