# Generated by Django 4.2.1 on 2023-06-04 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0004_remove_tasklist_lists_tasklist_tasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklist',
            name='tasks',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='lists.task'),
        ),
    ]
